# Generated by Django 4.0 on 2021-12-21 12:48

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid_name', models.CharField(max_length=100)),
                ('kid_age', models.IntegerField()),
                ('parent_num', phone_field.models.PhoneField(max_length=31, unique=True)),
                ('parent_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=300)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('food_group', models.CharField(blank=True, choices=[('F', 'Fruit'), ('V', 'Vegetable'), ('G', 'Grain'), ('P', 'Protein'), ('D', 'Dairy')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kids.kid')),
            ],
        ),
    ]
